// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_Localization_SQL.Models
{
    public partial class Language
    {
        public string LangKey { get; set; }
        public string LangZhTw { get; set; }
        public string LangEnUs { get; set; }
    }
}