// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MVC_Localization_SQL.Models
{
    public partial class TeachContext : DbContext
    {
        public TeachContext()
        {
        }

        public TeachContext(DbContextOptions<TeachContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Language> Language { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Language>(entity =>
            {
                entity.HasKey(e => e.LangKey);

                entity.Property(e => e.LangKey)
                    .HasMaxLength(50)
                    .HasColumnName("Lang_Key");

                entity.Property(e => e.LangEnUs)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("Lang_enUS");

                entity.Property(e => e.LangZhTw)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("Lang_zhTW");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}